AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Default: Prod

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yml
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions
      PackageType: Zip
      Runtime: python3.9
      Handler: create_user.handle
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId: !Ref Api