version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v45dc6tpzhx7"
s3_prefix = "test-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"Prod\""
image_repositories = []
disable_rollback = true
